image: cly0896/dm-mono-nunit

before_script:
  - nuget restore -NonInteractive
  - mapfile BuildConfiguration < BUILD

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    #Build DLLs
    - echo "BuildNum:${BuildConfiguration[0]}"
    #Build DLLs in Release mode
    - msbuild Build.proj /p:Configuration=Release /p:Platform="Any CPU" /p:build_number=${BuildConfiguration[0]}
  artifacts:
    paths:
      - "Admin-API-SDK/bin/Release/"
      - "Admin-API-Unit Tests-461/bin/Release/"
     
test:
  stage: test
  script:
    #Write Config File from Environment Variables
    - echo "EncryptionKey:"$EncryptionKey > "Admin-API-Unit Tests-461/Test Credentials/Credentials.txt"
    - echo "Email:"$Email >> "Admin-API-Unit Tests-461/Test Credentials/Credentials.txt"
    - echo "AutomationID:"$AutomationID >> "Admin-API-Unit Tests-461/Test Credentials/Credentials.txt"
    #Change directory and run unit tests
    - nunit "Admin-API-Unit Tests-461/bin/Release/Admin-API-Unit Tests-461.dll" --result 461Result.xml
  artifacts:
    paths:
      - "461Result.xml"
  dependencies:
    - build
      
release:
  stage: deploy
  only:
    - tags
  script:
    #Copy DLLs to lib folder for NuGet
    - mkdir -p "lib/net461" && cp "Admin-API-SDK/bin/Release/DataMotion Admin Library.dll" "lib/net461/DataMotion Admin Library.dll"
    - sed -i "s/version-num/${BuildConfiguration[0]}/g" AdminLibrary.nuspec
    - sed -i "s/author-name/DataMotion/g" AdminLibrary.nuspec
    - sed -i "s/copyright-date/Copyright 2018/g" AdminLibrary.nuspec
    - nuget pack Admin-API-SDK/AdminLibrary.nuspec
    - nuget setApiKey $ApiKey -Source https://api.nuget.org/v3/index.json
    - nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
  environment:
    name: nuget
  dependencies:
    - build